export const SET_LOADING_DELIVERIES = 'SET_LOADING_DELIVERIES';

export const SET_LOADING_DELIVERY = 'SET_LOADING_DELIVERY';

export const SET_UPDATING_STATUS = 'SET_UPDATING_STATUS';

export const SET_DELIVERIES = 'SET_DELIVERIES';

export const SET_DELIVERY = 'SET_DELIVERY';

export const CLEAR_DELIVERY = 'CLEAR_DELIVERY';
