export const SET_LOADING_DELIVERIES = 'SET_LOADING_DELIVERIES';

export const SET_LOADING_DELIVERY = 'SET_LOADING_DELIVERY';

export const SET_DELIVERED_STATUS = 'SET_DELIVERED_STATUS';

export const SET_UNDELIVERED_STATUS = 'SET_UNDELIVERED_STATUS';

export const SET_MAKING_ACTIVE = 'SET_MAKING_ACTIVE';

export const SET_DELIVERIES = 'SET_DELIVERIES';

export const SET_DELIVERY = 'SET_DELIVERY';

export const SET_ACTIVE = 'SET_ACTIVE';

export const SET_UPDATED_STATUS = 'SET_UPDATED_STATUS';

export const CLEAR_DELIVERY = 'CLEAR_DELIVERY';
